[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlinker.ld"
]

runner = """
    qemu-system-riscv64 \
    -machine virt -bios none \
    -m 128M -smp 3 -nographic \
    -drive file=fs.img,if=none,format=raw,id=x0 \
    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 \
    -kernel
"""
# -S -gdb tcp::12345

[term]
verbose = true
